import { Octokit } from "@octokit/rest";
import type { TriageResult, PRDetails, FailureContext, FailureCard } from "../collector/types.js";

/**
 * Create a pull request with the fix
 */
export async function createPullRequest(
  octokit: Octokit,
  owner: string,
  repo: string,
  baseBranch: string,
  headBranch: string,
  result: TriageResult,
  context: FailureContext,
  titleTemplate: string
): Promise<PRDetails> {
  const title = formatTitle(titleTemplate, result, context);
  const body = formatPRBody(result, context, owner, repo);

  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    body,
    head: headBranch,
    base: baseBranch
  });

  // Add labels
  const labels = ["greenlit", "auto-fix"];
  if (result.confidence) {
    labels.push(`confidence-${result.confidence}`);
  }

  await octokit.rest.issues.addLabels({
    owner,
    repo,
    issue_number: pr.number,
    labels
  });

  console.log(`   PR created: ${pr.html_url}`);

  return {
    prNumber: pr.number,
    prUrl: pr.html_url,
    branchName: headBranch
  };
}

/**
 * Post a comment on the original PR/commit
 */
export async function postComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  context: FailureContext,
  result: TriageResult,
  prDetails?: PRDetails
): Promise<string | undefined> {
  const body = formatCommentBody(result, context, prDetails);

  // Try to find associated PR
  const { data: prs } = await octokit.rest.repos.listPullRequestsAssociatedWithCommit({
    owner,
    repo,
    commit_sha: context.sha
  });

  if (prs.length > 0) {
    // Post on the PR
    const { data } = await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prs[0].number,
      body
    });
    console.log(`   Comment posted on PR #${prs[0].number}`);
    return data.html_url;
  } else {
    // Post on the commit
    const { data } = await octokit.rest.repos.createCommitComment({
      owner,
      repo,
      commit_sha: context.sha,
      body
    });
    console.log(`   Comment posted on commit ${context.sha.substring(0, 7)}`);
    return data.html_url;
  }
}

/**
 * Format PR title from template
 */
function formatTitle(template: string, result: TriageResult, context: FailureContext): string {
  // Extract a short summary from the fix
  const summary = result.rootCause.split("\n")[0].slice(0, 50);

  return template
    .replace("{failure_type}", context.failureType)
    .replace("{summary}", summary)
    .replace("{branch}", context.branch);
}

/**
 * Format full PR body with RCA
 */
function formatPRBody(
  result: TriageResult,
  context: FailureContext,
  owner: string,
  repo: string
): string {
  const runUrl = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;

  return `## 🤖 Greenlit Auto-Fix

This PR was automatically generated by **Greenlit** to fix a CI failure.

| | |
|---|---|
| **Failed Run** | [#${context.runId}](${runUrl}) |
| **Branch** | \`${context.branch}\` |
| **Commit** | \`${context.sha.substring(0, 7)}\` |
| **Failure Type** | ${context.failureType} |
| **Confidence** | ${result.confidence?.toUpperCase() || "N/A"} |

---

## 📋 Root Cause Analysis

### Error Signature
\`\`\`
${context.errorSignature}
\`\`\`

### Root Cause
${result.rootCause}

---

## 🧾 Evidence

${context.evidence?.file ? `- **File**: \`${context.evidence.file}\`` : "- **File**: (not detected)"}
${context.evidence?.line ? `\n- **Line**: \`${context.evidence.line}\`` : "\n- **Line**: (not detected)"}
${context.evidence?.job ? `\n- **Job**: ${context.evidence.job}` : "\n- **Job**: (not detected)"}
${context.evidence?.step ? `\n- **Step**: ${context.evidence.step}` : "\n- **Step**: (not detected)"}

${context.evidence?.excerpt ? `\n\n\`\`\`\n${context.evidence.excerpt}\n\`\`\`` : ""}

---

## 🔧 Fix Applied

${result.fixSummary}

---

## ✅ Verification

The fix was verified by re-running the failing command.

<details>
<summary>Verification Output</summary>

\`\`\`
${result.verificationLog.slice(-3000)}
\`\`\`

</details>

---

## 📝 Changes

<details>
<summary>View Diff</summary>

\`\`\`diff
${result.patchDiff}
\`\`\`

</details>

---

> ⚠️ **Note**: This is an automated fix. Please review carefully before merging.
>
> 🔑 **Fingerprint**: \`${context.fingerprint}\`
>
> Generated by [Greenlit](https://github.com/Avinier/greenlit)
`;
}

/**
 * Format comment body for non-PR situations
 */
function formatCommentBody(
  result: TriageResult,
  context: FailureContext,
  prDetails?: PRDetails
): string {
  if (result.failureCard) {
    return formatFailureCardComment(result.failureCard, context, result, prDetails);
  }

  const statusEmoji = result.success ? "✅" : "❌";
  const statusText = result.success ? "Fix Generated" : "Analysis Complete";

  let body = `## ${statusEmoji} Greenlit: ${statusText}

**Failure Type**: ${context.failureType}
**Routing Decision**: ${result.routingDecision}
**Confidence**: ${result.confidence || "N/A"}

### Error Signature
\`\`\`
${context.errorSignature}
\`\`\`

### Root Cause
${result.rootCause}
`;

  if (result.success && prDetails) {
    body += `
---

### 🎉 Fix PR Created

**[PR #${prDetails.prNumber}](${prDetails.prUrl})** - Ready for review

The fix has been verified and a PR has been created automatically.
`;
  } else if (!result.success) {
    body += `
---

### Recommendation

${result.fixSummary}
`;
  }

  body += `
---

<sub>🔑 Fingerprint: \`${context.fingerprint}\` | Generated by [Greenlit](https://github.com/Avinier/greenlit)</sub>
`;

  return body;
}

function formatFailureCardComment(
  card: FailureCard,
  context: FailureContext,
  result: TriageResult,
  prDetails?: PRDetails
): string {
  const jobStep = [card.job, card.step].filter(Boolean).join(" / ");
  const ownerLine = card.owner
    ? `${card.owner.owner} (${card.owner.source})`
    : "unassigned";
  const ownerReason = card.owner?.reason ? `- **Why**: ${card.owner.reason}` : "";
  const memoryLines = formatMemoryLines(card);

  let body = `## 🚨 Greenlit Failure Card

**Workflow**: ${card.workflowName}
${jobStep ? `**Job/Step**: ${jobStep}` : "**Job/Step**: (not detected)"}
**Failure Type/Class**: ${card.failureType} / ${card.failureClass}
**Routing**: ${card.routingDecision}
**Assigned Owner**: ${ownerLine}
${ownerReason}

### Error Signature
\`\`\`
${card.errorSignature}
\`\`\`

### Evidence
${card.evidence?.file ? `- **File**: \`${card.evidence.file}\`` : "- **File**: (not detected)"}
${card.evidence?.line ? `\n- **Line**: \`${card.evidence.line}\`` : "\n- **Line**: (not detected)"}
${card.evidence?.job ? `\n- **Job**: ${card.evidence.job}` : "\n- **Job**: (not detected)"}
${card.evidence?.step ? `\n- **Step**: ${card.evidence.step}` : "\n- **Step**: (not detected)"}

${card.evidence?.excerpt ? `\n\n\`\`\`\n${card.evidence.excerpt}\n\`\`\`` : ""}

### Recommended Action
${card.action}
`;

  if (memoryLines) {
    body += `\n---\n\n### Incident Memory\n${memoryLines}\n`;
  }

  if (result.success && prDetails) {
    body += `
---

### Fix Suggested

**[PR #${prDetails.prNumber}](${prDetails.prUrl})** - Ready for review
`;
  }

  body += `

<sub>🔑 Fingerprint: \`${context.fingerprint}\` | Generated by Greenlit</sub>
`;

  return body;
}

function formatMemoryLines(card: FailureCard): string {
  const memory = card.memory;
  if (!memory?.seenBefore) return "";

  const lines = [
    `- **Last Seen**: ${memory.lastSeen || "unknown"}`,
    `- **Last Outcome**: ${memory.lastOutcome || "unknown"}`
  ];

  if (memory.lastOwner) {
    lines.push(`- **Last Owner**: ${memory.lastOwner}`);
  }
  if (memory.lastResolution) {
    lines.push(`- **Last Resolution**: ${memory.lastResolution}`);
  }
  if (memory.threadUrl) {
    lines.push(`- **Thread**: ${memory.threadUrl}`);
  }

  return lines.join("\n");
}

/**
 * Format RCA markdown for standalone output
 */
export function formatRCAMarkdown(result: TriageResult, context: FailureContext): string {
  return `# Greenlit RCA Report

**Repository**: ${context.repo}
**Branch**: ${context.branch}
**Commit**: ${context.sha}
**Run ID**: ${context.runId}
**Generated**: ${new Date().toISOString()}

---

## Summary

**Status**: ${result.success ? "✅ Fixed" : "❌ Not Fixed"}
**Failure Type**: ${context.failureType}
**Failure Class**: ${context.failureClass}
**Routing**: ${result.routingDecision}
**Confidence**: ${result.confidence}
**Owner**: ${result.ownerAssignment?.owner || "unassigned"}

---

## Error Signature

\`\`\`
${context.errorSignature}
\`\`\`

---

## Root Cause

${result.rootCause}

---

## Incident Memory

${result.memory?.seenBefore ? `- **Last Seen**: ${result.memory.lastSeen || "unknown"}\n- **Last Outcome**: ${result.memory.lastOutcome || "unknown"}` : "No prior incidents recorded."}

---

## Evidence

${context.evidence?.file ? `- **File**: \`${context.evidence.file}\`` : "- **File**: (not detected)"}
${context.evidence?.line ? `\n- **Line**: \`${context.evidence.line}\`` : "\n- **Line**: (not detected)"}
${context.evidence?.job ? `\n- **Job**: ${context.evidence.job}` : "\n- **Job**: (not detected)"}
${context.evidence?.step ? `\n- **Step**: ${context.evidence.step}` : "\n- **Step**: (not detected)"}

${context.evidence?.excerpt ? `\n\n\`\`\`\n${context.evidence.excerpt}\n\`\`\`` : ""}

---

## Fix Summary

${result.fixSummary}

---

## Patch

\`\`\`diff
${result.patchDiff || "(no changes)"}
\`\`\`

---

## Verification

\`\`\`
${result.verificationLog || "(no verification run)"}
\`\`\`

---

**Fingerprint**: \`${context.fingerprint}\`
`;
}
